### PR TITLE
Fix increment bugs

### LINKED ISSUE #220: [PE-D][Tester E] Possible floating pt error when incementing (by negative) salary
As can be seen, first decrement works perfectly fine, but after second decrement, repeating 9-s appear. Might be a floating point problem? Unsure. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: xavierpok/ped#4

### LINKED ISSUE #231: [PE-D][Tester C] Format error displaying salary
Not sure if its meant to be like this but above a certain value the displayed salary is formatted in this different way

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: jylow/ped#1

### LINKED ISSUE #232: [PE-D][Tester E] `increment` sometimes does not add salaries correctly
Before : 

After  :

 Might be due to the almost-identical persons or maybe the dynamic sorting you've implemented? It seems that one john doe got incremented twice.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: xavierpok/ped#7

### LINKED ISSUE #235: [PE-D][Tester E] Display of person in error report feedback does not reflect bugged salary field
Should be relatively minor given that this state should not be entered at all

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: xavierpok/ped#9

### LINKED ISSUE #237: [PE-D][Tester D] Data file incorrectly named
The file where the EmployeeManager data is automatically  saved as a JSON file is not named `employeemanager.json` but rather `addressbook.json` which may be confusing for users who wish to edit the JSON file. Perhaps you can edit the name of the file in your UG or your code?

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: lunaroddity/ped#5

### PR DESCRIPTION
**Pull request by Goh-Li-Ting**
fixes #237 
fixes #235 
fixes #232 
fixes #231 
fixes #220

### CODE REVIEW

**Review by aexolate — CHANGES_REQUESTED** [review]
INFO: ----------------[USER COMMAND][increment 1000000000000000000000000000]
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

when `increment 1000000000000000000000000000` is input

**Comment by Goh-Li-Ting** [comment]
@aexolate Thanks for catching these bugs! 

The first bug is because the input exceeds the maximum possible long. Are we allowed to add new checks and error messages in 1.4?

Second bug is probably due to overflow as the input to increment is too large which is a similar issue as above.

**Comment by aexolate** [comment]
@Goh-Li-Ting Since it causes an unhandled exception, I think it could be counted as a bug? Perhaps we could defend using Q6 of FAQ since the exception doesn't show any error message on the application status box.

> Q6: Can we tweak error/help messages (or other text shown to the user)?
> A: Only if the current text is incorrect (i.e., a bug). Adding more information or otherwise 'enhancing' the text is not allowed.

**Comment by Goh-Li-Ting** [comment]
@aexolate 
> Since it causes an unhandled exception, I think it could be counted as a bug? Perhaps we could defend using Q6 of FAQ since the exception doesn't show any error message on the application status box.

Okay, thank you! I'll go and fix this!

> But I thought this exceeding data type limit was addressed in v1.3 with a proper error message? So we can keep the same behaviour

It seems like the maximum value of a double is much much larger than that of a long so the users won't be able to input enough values to exceed the maximum value of a double.
This error message is also shown during the execution of the command instead of during the parsing of the command (which is where the error is at now).

**Comment by Goh-Li-Ting** [comment]
The behaviour of the `increment` command behaves the same. It would be better to check the validity of the increment properly in `isValidIncrement` but to be able to catch both bugs, I think it would need to have a maximum increment, which seems to be a change to the feature.

File: src/main/java/seedu/address/model/person/SalaryParserUtil.java [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+        int decimalPlaceIndex = stringBuilder.length() - Salary.NUM_OF_DECIMAL_PLACES;
+        stringBuilder.insert(decimalPlaceIndex, ".");
+        return stringBuilder.toString();
+    }
+
+    /**
+     * Adds zeros to the front of the {@code stringBuilder} from index {@code start} until the string has at least
+     * ({@code Salary.NUM_OF_DECIMAL_PLACES} + 1) digits.
+     */
+    private static void addZerosToFront(StringBuilder stringBuilder, int start) {
```
Comment (aexolate) [inline src/main/java/seedu/address/model/person/SalaryParserUtil.java:33]: I think this function can be simplified unless I am misunderstanding the intend. But I think its fine to keep the current way too.

```
jshell> String val = "-123";
val ==> "-123"

jshell> String.format("%06d", Long.parseLong(val));
$13 ==> "-00123"
```

File: src/main/java/seedu/address/commons/core/increment/Increment.java [hunk 2]
```diff
@@ -3,14 +3,18 @@
 import static java.util.Objects.requireNonNull;
 import static seedu.address.commons.util.AppUtil.checkArgument;
 
+import seedu.address.model.person.Salary;
+import seedu.address.model.person.SalaryParserUtil;
+
 /**
  * Represents an increment.
  */
 public class Increment {
```
Comment (aexolate) [inline src/main/java/seedu/address/commons/core/increment/Increment.java:12]: I think ideally, the `Increment` constructor should have taken in a `long` argument already, since the IncrementCommandParser should be parsing the raw string input to send the required data type to the Command.

But for now we can probably merge this first so clear the bugs, then improve code quality if we still have time

**Review by aexolate — APPROVED** [review]
LGTM, but might need to consider if some of the changes stepped into the feature change territory.

The bugs reported appears to be fixed now - no more floating point errors and overflow exceptions,

**Comment by Weiennn** [comment]
`edit 1 s/1000000000000000000000000000` throws an uncatched error

File: src/main/java/seedu/address/model/person/Salary.java [hunk 3]
```diff
@@ -11,17 +11,20 @@
  */
 
 public class Salary implements Comparable<seedu.address.model.person.Salary> {
-    public static final double MAXIMUM_SALARY = 1000000000;
+    public static final int MAXIMUM_SALARY = 1000000000;
+    public static final int NUM_OF_DECIMAL_PLACES = 2;
+    public static final long MAXIMUM_SALARY_LONG =
+            SalaryParserUtil.addZerosToBack(MAXIMUM_SALARY, NUM_OF_DECIMAL_PLACES);
     public static final String MESSAGE_CONSTRAINTS = String.format(
-            "Salary should only contain numbers, be non-negative, contain at most 2 decimals, and be at most %.2f",
```
[the remark this answers is not in the document]
Comment (Goh-Li-Ting) [reply src/main/java/seedu/address/model/person/Salary.java:16]: Thank you for pointing this out! I have made the changes, do let me know if I missed any!

File: src/main/java/seedu/address/model/person/SalaryParserUtil.java (hunk 1 above)
Comment (Goh-Li-Ting) [reply src/main/java/seedu/address/model/person/SalaryParserUtil.java]: Thank you for the suggestion! I have modified the function!

File: src/main/java/seedu/address/commons/core/increment/Increment.java (hunk 2 above)
Comment (Goh-Li-Ting) [reply src/main/java/seedu/address/commons/core/increment/Increment.java:12]: Yup, that's a good point! I'm not sure what error message to show to the users though, because the increment needs to be below max long / 100, but implementing a maximum increment feels like a feature change and I can't think of another way to implement this

File: src/main/java/seedu/address/model/person/Salary.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (aexolate) [reply src/main/java/seedu/address/model/person/Salary.java:16]: lgtm

File: src/main/java/seedu/address/commons/core/increment/Increment.java (hunk 2 above)
Comment (aexolate) [reply src/main/java/seedu/address/commons/core/increment/Increment.java:12]: That's true, it's probably not possible to introduce a new error message at the parser now. It should be fine!

**Review by Weiennn — APPROVED** [review]
LGTM
